# This code generates html code for the decorations displayed on both sides of the screen.
# In projects.html, the div class 'left_decorations' is generated by the first for loop below
# and the div class 'right_decorations' is generated by the second for loop.

# left decorations
for i in range(0, 20):
	print('<img id=\"shape_left\" src=\"images/circle.svg\">')
	print('<img id=\"shape_left\" src=\"images/triangle.svg\">')

# right decorations
for i in range(0, 20):
	print('<img id=\"shape_right\" src=\"images/circle.svg\">')
	print('<img id=\"shape_right\" src=\"images/triangle.svg\">')